name: "Setup nf-test"
description: "Install nf-test and add it to the PATH"
author: "nf-core"
inputs:
  version:
    description: "The nf-test version to download (if necessary) and use. Example: 0.7.0. Installs latest by default"
    required: true
    default: "" # latest
runs:
  using: "node20"
  main: "index.js"
