on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A test to install nf-test
    strategy:
      matrix:
        NF-TEST_VER:
          - ""
          - "0.7.0"
          - "0.7.1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: nf-core/setup-nextflow@v1
      - name: nf-test install action step
        uses: ./
        with:
          version: "${{ matrix.NF-TEST_VER }}"
      - name: Smoke test
        run: nf-test version
