on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build action script
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
  test:
    runs-on: ubuntu-latest
    name: A test to install nf-test
    needs: build
    strategy:
      matrix:
        NF-TEST_VER:
          - "0.8.4"
          - "0.8.0"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: nf-core/setup-nextflow@v2

      - name: nf-test install action step
        uses: ./
        with:
          version: "${{ matrix.NF-TEST_VER }}"
      - name: Show PATH
        run: echo $PATH
      - name: Smoke test
        run: nf-test version
