on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A test to install nf-test
    strategy:
      matrix:
        NF-TEST_VER:
          - '0.8.4'
          - '0.8.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: nf-core/setup-nextflow@v2
      - name: nf-test install action step
        uses: ./
        with:
          version: '${{ matrix.NF-TEST_VER }}'
      - name: Show PATH
        run: echo $PATH
      - name: Smoke test
        run: nf-test version
